### ISSUE TITLE
Greenify cx_Oracle Hint

### ISSUE THREAD

**Issue by sgratzl** [oracle/python-cx_Oracle#126]
hi,

for those of you using cx_Oracle in a gevent environment. I found a way using the [greenify](https://pypi.python.org/pypi/greenify) package to patch the shared library and be green. 

```
import greenify
greenify.greenify()
assert greenify.patch_lib('/opt/oracle/instantclient_12_2/libclntsh.so.12.1')
```

before the cx_Oracle package is loaded

**Comment by Deneby67** [comment]
cx_oracle 5.3

At high load an error occurs
KPEDBG_HDL_PUSH_FCPTRMAX

**Comment by Deneby67** [comment]
threaded=True does not help

**Comment by cjbj** [comment]
@Deneby67 Even if your problem is related to Greenify, please open a new issue and give some useful detail.

**Comment by PMLP-novo** [comment]
I was able to replicate the KPEDBG_HDL_PUSH_FCPTRMAX error it seems to happen on very high loads. Since the cx_oracle package is not supporting parallelization. Attacking the aplication below with `siege -r 500 -c 50 http://localhost:8088/` have me the error, see https://stackoverflow.com/questions/65959615/sqlalchemy-gevent-cx-oracle-pool-size-stays-at-1 . My solution was to set the pool size to 10, which is still an improvement but seemed safe for my usecases. For more info see https://github.com/mattn/go-oci8/issues/32 and if you know what "KPEDBG_HDL_PUSH_FCPTRMAX" means please tell me
 https://stackoverflow.com/questions/68996800/what-does-the-error-kpedbg-hdl-push-fcptrmax-mean.

```
import greenify

greenify.greenify()
assert greenify.patch_lib("/usr/lib/oracle/19.5/client64/lib/libclntsh.so.19.1")

from gevent.monkey import patch_all
patch_all()

from gevent.pywsgi import WSGIServer
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

username = '<hidden>'
password = '<hidden>'
host = '<hidden>'

url = 'oracle+cx_oracle://{}:{}@{}'.format(username, password, host)

engine = create_engine(url, pool_size=200)
Session = sessionmaker(bind=engine)

def application(env, start_response):

    session = Session()
    result = session.execute('select 1+1 from dual')
    result.fetchall()
    session.close()

    print('Status:', engine.pool.status())

    start_response('200 OK', [('Content-Type', 'text/html')])
    return [b'<b>hello world</b>']

if __name__ == '__main__':
    print('Serving on 8088...')
    WSGIServer(('127.0.0.1', 8088), application, log=None).serve_forever()
```

This issue is linked to https://github.com/douban/greenify/issues/19

**Comment by cjbj** [comment]
Are you using Oracle's session pool? https://docs.sqlalchemy.org/en/14/dialects/oracle.html#using-cx-oracle-sessionpool

Why not use a more recent Oracle client version?
