### ISSUE TITLE
Request to add a SDOOutputTypeHandler tutorial

### ISSUE THREAD

**Issue by christofer-f** [oracle/python-cx_Oracle#146]
This is a request to extend the otherwise excellect tutorial: "Python-and-Oracle-Database-12c-Scripting-for-the-Future" found in the sample directory with an OutputTypeHandler for SDO_GEOMETRY objects.

I am trying to understand the concept of OutputTypeHandlers.
But I have problem to get it to work for MDSYS.SDO_GEOMETRY objects

I get a lot of hints in the tutorial like the functions listed below but I still can't get it to work...

def SDOInputTypeHandler(cursor, value, numElements):
    if isinstance(value, mySDO):
        return cursor.var(cx_Oracle.OBJECT, arraysize = numElements,
                inconverter = SDOInConverter, typename = objType.name)

def dumpobject(obj, prefix = "  "):
...

Br,
Christofer

**Comment by christofer-f** [comment]
Why does this code give me an error?

Pseudo code that give error: cx_Oracle.DatabaseError: ORA-00932: 
inconsistent datatypes: expected CHAR got ADT

def bar(obj):
    return "dummy value"

def foo(cursor, name, defaultType, size, precision, scale):
    return cursor.var(str, 100, cursor.arraysize, outconverter=bar)

cur.outputtypehandler = foo
cur.execute("select LOCATION from PLACES")
for row in cur:
    print(row)

**Comment by anthony-tuininga** [comment]
The variable that you create is actually used by Oracle, so you need something like the following instead:

```python
def foo(cursor, name, defaultType, size, precision, scale):
    return cursor.var(cx_Oracle.OBJECT, arraysize=cursor.arraysize, typename="SDO_GEOMETRY", outconverter=bar)
```

**Comment by anthony-tuininga** [comment]
Can you provide a bit more detail on what you would like to see for the output type handler example for SDO_GEOMETRY?

**Comment by christofer-f** [comment]
Hi again...
I think this issue can be closed. 
I have provided a code sample that should work with minimal modification.
If this can be done in a more general or complete way please comment.

Br,
Christofer


```
import sys
import cx_Oracle
import global_def


def ObjectRepr(obj):
    if obj.type.iscollection:
        returnValue = []
        for value in obj.aslist():
            if isinstance(value, cx_Oracle.Object):
                value = ObjectRepr(value)
            returnValue.append(value)
    else:
        returnValue = {}
        for attr in obj.type.attributes:
            value = getattr(obj, attr.name)
            if value is None:
                continue
            elif isinstance(value, cx_Oracle.Object):
                value = ObjectRepr(value)
            returnValue[attr.name] = value
    return returnValue


def outputtypehandler(cursor, name, defaultType, size, precision, scale):
    if defaultType == cx_Oracle.NUMBER:
        return cursor.var(cx_Oracle.NUMBER, arraysize=cursor.arraysize)
    if defaultType == cx_Oracle.STRING:
        return cursor.var(cx_Oracle.STRING, arraysize=cursor.arraysize)
    if defaultType == cx_Oracle.OBJECT:
        return cursor.var(cx_Oracle.OBJECT, arraysize=cursor.arraysize, typename="SDO_GEOMETRY",
                          outconverter=ObjectRepr)
    if defaultType == cx_Oracle.CLOB:
        return cursor.var(str, arraysize=cursor.arraysize)


def makeDictFactory(cursor):
    columnNames = [d[0] for d in cursor.description]

    def createRow(*args):
        return dict(zip(columnNames, args))

    return createRow


def main():
    with cx_Oracle.connect(global_def.connectString) as con:

        try:
            cur = con.cursor()
            cur.outputtypehandler = outputtypehandler
            cur.execute(
                "select ID, LOCATION, SDO_UTIL.TO_WKTGEOMETRY(LOCATION) AS WTK  from PLACES'")
            cur.rowfactory = makeDictFactory(cur)
            for result in cur:
                print(result)
            cur.close()
        except:
            e = sys.exc_info()[0]
            print(e)


if __name__ == '__main__':
    main()

```

**Comment by anthony-tuininga** [comment]
The only comment I'll make about your suggested code is regarding your output type handler. If you return the value None (or don't return anything at all), the normal default processing takes place. So you can remove your checks for cx_Oracle.NUMBER and cx_Oracle.STRING. Also, for your check for cx_Oracle.CLOB, you should use cx_Oracle.LONG_STRING in order to allow for strings longer than the default size (4000 bytes).

If you were looking for code to transform SDO_GEOMETRY to GeoJSON, there is PL/SQL code available (https://spatialdbadvisor.com/oracle_spatial_tips_tricks/206/sdo2geojson for example) and you could use this as the basis for transforming SDO_GEOMETRY to GeoJSON in Python. There is an old and fairly incomplete Python version (https://pypi.python.org/pypi/sdo/0.6.5) that also does this. Oracle provides a converter from GeoJSON to SDO but not the other way around -- but as noted by the above links, it wouldn't be terribly complicated to do so. Judging from the various links that I found while looking for this, there is some demand for it -- so if you wrote something I suspect it would be appreciated. :-)

**Comment by anthony-tuininga** [comment]
Our spatial team has developed a code sample that should help you out. I'll include a link to that sample before I close this issue.

https://github.com/oracle/python-cx_Oracle/blob/master/samples/SpatialToGeoPandas.py
