### ISSUE TITLE
question about cx_Oracle 6.0b1

### ISSUE THREAD

**Issue by behrm** [oracle/python-cx_Oracle#16]
I found that cx_Oracle version 6.0b1 solves a problem I have with versions 5.2.1. and 5.3 (i.e. getting ORA 01461 when inserting String or Unicode longer than 4000 Byte into a CLOB-field).  My Question is, if I could use Version 6.0 Beta for production use or better wait for a later version? Can you please give a advice?

**Comment by rafaelreuber** [comment]
You never should use a beta version for a production environment. A possible bug could produce unexpected code on your code.You never should use a beta version for a production environment. An possible bug could produce unexpected code on your code.

**Comment by anthony-tuininga** [comment]
Rafael's advice is generally good advice to follow. There is a higher probability that there is a bug in 6.0b1 then there is in 5.3. That said, I have run quite a few tests on 6.0b1 and no problems have been discovered so far. The underlying layer (ODPI-C) has also been tested in a number of other languages (more on that to follow at a later point). The main reason for making this a beta release instead of a regular release is due to the significant changes and a desire to get feedback before making it a regular release. In short, run your own tests on your application -- and if it works for you, there is nothing preventing you from using it in production.
