### ISSUE TITLE
Unable to terminate execute(sql)

### ISSUE THREAD

**Issue by dsmicoo** [oracle/python-cx_Oracle#167]
I use cx_Oracle to execute SQL, and I want to kill SQL that takes more than 5 minutes to execute. But I don't know how long my SQL has been executing

**Comment by anthony-tuininga** [comment]
There are a number of ways to do this sort of thing. One of the simplest is to simply create a profile that specifies the maximum amount of resources that you would like sessions to take before an error is raised in that session. See [here](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/CREATE-PROFILE.html#GUID-ABC7AE4D-64A8-4EA9-857D-BEF7300B64C3). Note that this sort of question is best asked on a site like [AskTom](https://asktom.oracle.com/pls/apex/f?p=100:1000::::::) since it is not specific to cx_Oracle.

**Comment by cjbj** [comment]
You can also look at creating a sqlnet.ora file and set values for SQLNET.OUTBOUND_CONNECT_TIMEOUT, SQLNET.RECV_TIMEOUT and SQLNET.SEND_TIMEOUT etc. There are some links to Oracle Doc in https://oracle.github.io/node-oracledb/doc/api.html#connectionha that are relevant.
