### ISSUE TITLE
cx_Oracle-5.3-11g.win-amd64-py3.6.exe cannot install in Python 3.6.0 64 bit version

### ISSUE THREAD

**Issue by belongwqz** [oracle/python-cx_Oracle#2]
cx_Oracle-5.3-11g.win-amd64-py3.6.exe cannot install in Python 3.6.0 64 bit version(but seems like cx_Oracle-5.3-11g.win-amd64-py3.5.exe work for Python 3.5.x 64 bit version good):
Python version 3.6-32 required, which was not found in the registry

**Comment by anthony-tuininga** [comment]
I'll take a look.

**Comment by anthony-tuininga** [comment]
It seems like this is a known [issue](https://sourceforge.net/p/pywin32/bugs/742). There are a few workarounds noted there that may work for you. I'll provide one more here.

The executable files are really just stubs with a zip file appended to them. So you can quite easily open the zip file and extract the cx_Oracle.pyd and place it directly in your site-packages directory or anywhere on PYTHONPATH. Nothing else needs to be done. The other files in the zip file are documentation which you can view online anyway.

This problem appears to be intermittent -- not everyone is affected by it. I am hoping to replace these with Python wheels which aren't affected by these issues. Currently because there are multiple versions of cx_Oracle for each Python version pip can't install the right one -- but I'm working on that right now. Would it be helpful to have wheels uploaded in spite of this restriction? Or are the workarounds provided adequate?

**Comment by belongwqz** [comment]
Thans, when copy cx_Oracle.cp36-win_amd64.pyd into “Python36\Lib\site-packages”, it works.

But I found another problem, when exec "select count(*) from xxx" return 0, the "cursor.description" does not return format "(name, type, display_size, internal_size, precision, scale, null_ok)" as told in cursor.rst about “Cursor.description”, but return <class 'tuple'>: ('__COUNT', <class 'cx_Oracle.NUMBER'>, 127, None, None, None, 1), then the precision and scale is both None.Code as fllow:
```
import cx_Oracle
connection = cx_Oracle.connect("xx", "xx", "xx")
sql = "SELECT COUNT(*) AS ct FROM xxx"  # the ct is 0
cursor.execute(sql)
print(cursor.description)
```

**Comment by anthony-tuininga** [comment]
Glad to hear you got things working. Regarding the cursor.description, it appears to be working as expected. The value None is returned for values in the tuple that are not meaningful -- which is what is happening in this case. What values were you expecting to see?

**Comment by belongwqz** [comment]
In the version 5.2.1, it returns "[('CT', <class 'cx_Oracle.NUMBER'>, 127, 22, 0, 0, 1)]", but in the lastest version is "[('CT', <class 'cx_Oracle.NUMBER'>, 127, None, None, None, 1)]",This'll rase TypeError in django(i use version 1.10.5) at "Python36\lib\site-packages\django\db\backends\oracle\base.py in _rowfactory, line 580",'>' not supported between instances of 'NoneType' and 'int'.So I think it's an inheritance problem.

**Comment by anthony-tuininga** [comment]
This was raised earlier (https://github.com/oracle/python-cx_Oracle/issues/1) and answered there. This is arguably a bug in Django and fortunately very easily fixed.

**Comment by anthony-tuininga** [comment]
I have uploaded new versions of the executable installers for Python 3.6 (64-bit) on Windows built with Python 3.6.1 which appear to have resolved the issue with the executable installers.

**Comment by belongwqz** [comment]
awesome， thx
