### ISSUE TITLE
DatabaseError on CentOS, cx_Oracle and Oracle Client

### ISSUE THREAD

**Issue by Terizian** [oracle/python-cx_Oracle#256]
1. What is your version of Python? Is it 32-bit or 64-bit?
3.7.1 64-bit (Anaconda)

2. What is your cx_Oracle version?
7.0.0

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
`connection = cx_Oracle.connect(user='username', password='password', dsn='dsn')`

4. What error(s) you are seeing?
`DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help`

5. What OS (and version) is Python executing on?
CentOS 7

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?
11g Administrator, and installed using the wizard on the CentOS server

7. What is your Oracle Database version?
11g

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
$ORACLE_HOME/lib

9. What Oracle environment variables did you set?  How *exactly* did you set them?
Set by modifying the bash_profile exactly like shown in previous issues and tutorials

10. Do you have a small, single Python script that immediately runs to show us the problem?
```
import cx_Oracle
connection = cx_Oracle.connect(user='username', password='password', dsn='dsn')
```

I have created a symlink for the lib folders but it still didn't solve the issue. SQLPlus works fine though.

**Comment by cjbj** [comment]
- You shouldn't set ORACLE_HOME for cx_Oracle 6+

- show us the output where you run SQL*Plus and then immediately run Python in the same terminal.

**Comment by cjbj** [comment]
@josip1911 you should NOT do that if you have Instant Client.   

I'm looking forward to seeing the blog.

**Comment by josip1911** [comment]
If I ommit 
os.environ["ORACLE_HOME"]...

db = cx_Oracle.connect('scott/jp@orcl')
cx_Oracle.DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help
None

Process finished with exit code 1

I have Oracle Client 18c on Fedora, and Oracle 18c database on OEL7. 

cx_driver used is 7. 

Tested with CPython (pipenv) and Anaconda distribution (conda env).

**Comment by cjbj** [comment]
@josip1911 you're not sharing enough info for me to go into tech details.  If you are linking cx_Oracle with Oracle client libraries from a local DB you obviously need to set ORACLE_HOME.  

But in my view you should be setting ORACLE_HOME where you set your other environment variables like ORACLE_BASE, NLS_LANG, LD_LIBRARY_PATH, ORA_SDTZ etc and that place is in the shell before you run Python.  Setting env variables in python scripts is error prone.  For a start it means you have to edit the script when you move it to a different environment or upgrade Oracle.  And if you do this consistently than all tools (e.g. SQL*Plus) will be using the same environment.

**Comment by josip1911** [comment]
@cjbj 
If you are linking cx_Oracle with Oracle client libraries from a local DB you obviously need to set ORACLE_HOME.
-------> No, I have only Oracle Client installed and ORACLE_HOME is needed. 
I'll test once case with instant client. 

I hope you understand that behaviour of Python in virtual env is different from normal one. 

As all Python deployments should be in virtual envs (pipenv, virtualenv, conda), you should set OH. 

You can see a bit of details at the end of article: 

https://www.josip-pojatina.com/en/python-oracle-connection-options/

**Comment by Terizian** [comment]
> * You shouldn't set ORACLE_HOME for cx_Oracle 6+
> * show us the output where you run SQL*Plus and then immediately run Python in the same terminal.

Please forgive my ignorance in the matter. It seems when I set ORACLE_HOME and run both sqlplus and python from the terminal it works but I have to run the command below first.
`. /home/usr/.bash_profile`
If I don't do so, it doesn't take the value of ORACLE_HOME and running sqlplus returns the error "command not found". On my Jupyter notebook, however, the same error that I have mentioned above is thrown.

Which environment variables should I be setting up to resolve the issue? This is how I am currently doing it:
`export ORACLE_HOME=/home/usr/app/product/11.2.0/client_1
export PATH=$ORACLE_HOME/bin:$PATH
export LD_LIBRARY_PATH=$ORACLE_HOME:$LD_LIBRARY_PATH`

**Comment by Terizian** [comment]
> @cjbj
> If you are linking cx_Oracle with Oracle client libraries from a local DB you obviously need to set ORACLE_HOME.
> -------> No, I have only Oracle Client installed and ORACLE_HOME is needed.
> I'll test once case with instant client.
> 
> I hope you understand that behaviour of Python in virtual env is different from normal one.
> 
> As all Python deployments should be in virtual envs (pipenv, virtualenv, conda), you should set OH.
> 
> You can see a bit of details at the end of article:
> 
> https://www.josip-pojatina.com/en/python-oracle-connection-options/

When I add the line setting the ORACLE_HOME variable to my code, it works.

Can you please advise on the best practices in this matter?

**Comment by josip1911** [comment]
For Python it's clear that you should always deploy your code in one of several available virtual envs to avoid package collision within your project. 
For that reason you need to set OH as I explain in a link, otherwise cx_oracle wouldn't correctly find necessary library. 

If you only try to replace some bash/kshell code with Python, and you are not using virtualization, you need to install cx_oracle in your system Python installation (which is wrong), and you need to set Oracle env as you wrote above (only OH is needed for Python & cx_oracle, while LD and PATH are for pure bash/sql*plus). 

Problem with such approach might arise when you'll add additional Python packages in a project, that can easily corrupt your system Python installation. 

That's the reason why my approach is recommended.

**Comment by cjbj** [comment]
@Terizian under the guess that you were using Oracle Instant Client and/or were coming from a previous version of cx_Oracle I mentioned not setting ORACLE_HOME.  I should have explicitly said "...if you are using Instant Client".  In the old days you needed the variable set during cx_Oracle install, even with Instant Client. Since Oracle doesn't recommend ORACLE_HOME being set for Instant Client, this was an annoyance for me. Luckily now that cx_Oracle installation doesn't need ORACLE_HOME set, there is no need to have it set unless you are linking cx_Oracle with the full Oracle Client or an Oracle DB installation (this is all [documented](http://cx-oracle.readthedocs.io/en/latest/installation.html)).  The best practice is to set whatever Oracle environment variables are needed in the shell that invokes the Python script.  I might make an exception for ORA_SDTZ if your application needs a single, fixed value for the time zone.

In non-Instant Client cases, you typically set the Oracle environment with `source  /usr/local/bin/oraenv`

@josip1911 it's great to see a post about cx_Oracle.  I disagree there is anything special about virtual envs.  The only factor is which of the three places you are getting Oracle client libraries from.  Most people are using Instant Client - particularly on Linux now you don't need a click through to download it, see http://yum.oracle.com/repo/OracleLinux/OL7/oracle/instantclient/x86_64/index.html.   

I would strongly recommend against setting ORACLE_HOME inside your application because (i) it's a pain to edit when the Oracle install changes (ii) it doesn't work for Instant Client, so your apps aren't portable (iii) most people are using Instant Client (iv) it's bad practice :)

Since you are all interested in setup you may like:
- https://yum.oracle.com/oracle-linux-python.html
- https://github.com/oracle/docker-images/tree/master/OracleInstantClient

**Comment by josip1911** [comment]
@cjbj
1. 
I thought the post started with CentOS, not Oracle Linux. 
2.
I mentioned virtualenv only in context how all Python projects are developed today. 
Never said it's something special. 
3. 
Setting in app or setting on command line are two choices. For conecting, only OH is enoughh. 
4. 
Example on my web is demo example, not a production. Sure you should replace hard coding part in app with configuration file in Python project from where you can read configuration dynamically. 
5. 
You always need to have env checking part in your Python app, to avoid issues when someone (sysadmin, other DBA...) change env settings (either oraenv or .bashrc/.bash_profile). You don't want to rely on terminal env in your app. 
The best would be to unset it and only set what is needed.

**Comment by anthony-tuininga** [comment]
@josip1911, the reason your code works is likely due to the fact that ODPI-C (upon which cx_Oracle is based) will look at the environment variable ORACLE_HOME and use it to determine the location of the Oracle Client libraries. This is intended, however, for full client and database installations, not for instant client installations -- so even though it "works" it isn't recommended. It also will not work on Windows. Instead you should follow the instructions that Chris provided. I hope that explains the situation!

**Comment by josip1911** [comment]
Just completed test with Ubuntu 18.04 and instant client 18c. 

You are right that situation is different without full Oracle Client, but only partly. 

It's true that only LD_LIBRARY_PATH is needed. 

Problem with env vars is in that, they are static and thus cannot be reloaded when you are running Python. 
For that reason, even if I set LD_LIBRARY_PATH env var inside Python, it won't be applied (it has to be set before running the Python script). 

That means when you run Python from command line with env set, everything is fine if you have LD_LIBRARY_PATH set. 

Problem is if you have to run virtual python env, or if you run Python program from Enterprise Scheduling System, in which case you'll get the error again.

The easiest solution (at least for Linux) is to add instant client path to ld.so.conf.d
in which case you'll have all situations covered (command line, enterprise scheduler and virtual environment). 

There are at least one other solution that I have, but it's more complicated one.

**Comment by anthony-tuininga** [comment]
@josip1911, yes, the easiest solution on Linux is to use ld.so.conf.d and it is definitely preferred over setting ORACLE_HOME.

@Terizian, have you managed to resolve your issues based on what you have seen here?

**Comment by Terizian** [comment]
Thank you all for the detailed explanation. I have managed to resolve the issue by the addition of the line below in my code even though I am using a full Oracle Client installation.

`os.environ["ORACLE_HOME"] = "path_to_ORACLE_HOME"`

**Comment by josip1911** [comment]
I summarize all my findings on teh following link:
https://www.josip-pojatina.com/en/python-oracle-instant-client-connection-setup-on-linux/

Feel free to comment if something is not accurate.

**Comment by anthony-tuininga** [comment]
Thanks, @Terizian. Based on that response and after looking at the blog entry made by @josip1911 I think I can safely close this now.
