### ISSUE TITLE
Failing to connect when DSN and Encoding are provided

### ISSUE THREAD

**Issue by dani29** [oracle/python-cx_Oracle#270]
The existence of the DSN in the function `connect()` causes a failure to connect, blaming Unknown encoding for the exception. I've discovered it while migrating from using a connection string to a DSN, and not sure how to proceed. 
 
I suspected there is something wrong with my AL32UTF8 encoding, but I do not see why it did work when connection string is used but not when a DSN is used. 
```python
import cx_Orcale

USER = ....
PASSWORD = ...
MY_HOST = ....
PORT = ...
MY_SERVICE = ...

def build_connection_string(user, pwd, host, port, service):
      return "{user}/{pwd}@{host}:{port}/{service}".format(
         user=user, pwd=pwd, host=host, port=port, service=service)

connection_string = build_connection_string(USER, PASSWORD, MY_HOST, PORT, MY_SERVICE)
dsn = cx_Oracle.makedsn(host=MY_HOST, port=PORT, service_name=MY_SERVICE)
DEFAULT_SQL_ENCODING = {"encoding": "AL32UTF8", "nencoding": "AL16UTF16"}
SOME_OTHER_ENCODING = {"encoding': 'UTF8", 'nencoding': "UTF16"}

# Works
conn = cx_Oracle.connect(connection_string, **DEFAULT_SQL_ENCODING)

# Throws "LookupError: unknown encoding: AL32UTF8"
dsn_connection_default_encoding = cx_Oracle.connect(
            user=USER
            password=PASSWORD
            dsn=dsn,
            **DEFAULT_SQL_ENCODING)

# Works
dsn_connection_default_encoding = cx_Oracle.connect(
            user=USER
            password=PASSWORD
            dsn=dsn,
            **SOME_OTHER_ENCODING)
```
Tested on both Python 2.7.15 and 2.7.12 with 64-bit, cx_Oracle version 7.0.0.
Connecting to Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

**Comment by cjbj** [comment]
What OS is python running on? What's the Oracle Client version?  If you are using Instant Client is it the Basic or Basic Light package?

**Comment by anthony-tuininga** [comment]
There is no reason to use the Oracle character set names -- especially if the translation between the Oracle character set names and the IANA names (that Python uses) is not working properly. Instead, use this:

```python
conn = cx_Oracle.connect(user=USER, password=PASSWORD, dsn=-dsn, encoding="UTF-8", nencoding="UTF-8")
```

That is the equivalent of AL32UTF8 (Oracle character set name) but using the IANA name instead.

**Comment by dani29** [comment]
@anthony-tuininga Makes sense. Though, I assume that AL16UTF16 should be mapped to UTF-16, not like in your example.

What I'm still not sure about is whether the correct behavior is to throw an Exception when DSN is used, and not to throw one when the connection string is provided. Am I missing anything?

**Comment by anthony-tuininga** [comment]
Right. Yes, it should be "UTF-16". Sorry about that!

I just tried your code -- as posted it had a lot of minor issues with it but I managed to get it working. The first connection attempt you say works doesn't for me on Python 3.7. I immediately get 
"LookupError: unknown encoding: AL32UTF8". Only the third one works -- as UTF16 is an alias for UTF-16. Trying on Python 2.7 I see the behaviour you are getting. I'll have to look into why that is happening and get back to you.

**Comment by anthony-tuininga** [comment]
Ok. The reason you're getting that error is because cx_Oracle needs to encode the strings you are passing into the character set expected by the database, but AL32UTF8 is not a valid encoding as far as Python is concerned. So you **must** use a valid Python encoding, or leave the encoding unspecified in order to use the NLS_LANG environment variable. Of course if you do that, you also take the risk that this is usable by the default Python encoding. It might make sense to change cx_Oracle so that the default encoding and nencoding parameters are "UTF-8" and drop the ability to use NLS_LANG since it is prone to misuse.

**Comment by dani29** [comment]
Appreciate the time you took debugging it!

From my perspective (admittedly, very inexperienced user of cx_Oracle), it was rather confusing given the fact Python and Oracle are using different encoding sets.
If I understand correctly, NLS_LANG is an acceptable default behavior, as sometimes it might make sense for the client to accept whatever encoding the server uses, and deal with the consequences. 
The issue that annoyed me more (and may be easier to fix) is that the error did not show up when I used a conn string, and did pop up when I used a DSN. That confused me as I was trying to figure out what's wrong with the connection, rather than I simply mis-used the encoding param.

**Comment by anthony-tuininga** [comment]
I've updated the documentation to make it clearer that a Python encoding is required. Note as well that in Python 2.7, unless you use Unicode strings, no errors are generated since it is assumed (by Python 2.x) that you know what you are doing and are passing an encoded string in the correct encoding -- but I wouldn't count on that behaviour as sooner or later you'll need to upgrade to Python 3.x anyway!
