### ISSUE TITLE
prefer .whl to .exe for windows

### ISSUE THREAD

**Issue by goldenbull** [oracle/python-cx_Oracle#28]
It seems more friendly to use wheel files for windows.
.whl will not affect Windows Control Panel. When there are multiple python envs in one system, .exe will have multiple entries in the Uninstall Panel.

**Comment by anthony-tuininga** [comment]
Wheels are available for cx_Oracle 6 which is currently in beta. Wheels were not possible before because they do not allow for multiple binaries for each Python version. In the meantime, if you wish to use the executable as the source of the module without running the installation, you can simply unzip the zip file attached to the executable (most zip utilities should do this automatically) and extract the .pyd file, then place that file anywhere on sys.path for your Python installation.

**Comment by cjbj** [comment]
The [cx_Oracle home page](https://oracle.github.io/python-cx_Oracle/index.html) has this tip for testing cx_Oracle 6 Beta:

> Install by issuing the command
> 
>`python -m pip install cx_Oracle --pre`
