### ISSUE TITLE
ORA-12704: character set mismatch when using python2.7 and unicode

### ISSUE THREAD

**Issue by ancc** [oracle/python-cx_Oracle#288]
#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
**python 2.7.13**
2. What is your cx_Oracle version?
**7.1.2**
3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

4. What error(s) you are seeing?
**DatabaseError: ORA-12704: character set mismatch**
5. What OS (and version) is Python executing on?
**Centos 6.8**
6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?
**instant client 12.2.0.1**
7. What is your Oracle Database version?
**12.2.0.1**
8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

9. What Oracle environment variables did you set?  How *exactly* did you set them?
**export ORACLE_HOME=/opt/oracle/instantclient
export NLS_LANG=AMERICAN_AMERICA.AL32UTF8**
10. Do you have a small, single Python script that immediately runs to show us the problem?

```
import traceback
import cx_Oracle

con = cx_Oracle.Connection('user/pass@db')
cur = con.cursor()
cur.execute("create table test(val varchar2(10 char))")
sql = "select coalesce(:val, val, 'test') val from test"
try:
    cur.execute(sql, {':val': u'test'})
except Exception as e:
    traceback.print_exc()
finally:
    cur.execute("drop table test")
cur.close()
con.close()
```
output
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    cur.execute(sql, {':val': u'test'})
DatabaseError: ORA-12704: character set mismatch
```
NLS parameters
```
PARAMETER							 VALUE
---------------------------------------------------------------- ----------------------------------------------------------------
NLS_LANGUAGE							 AMERICAN
NLS_TERRITORY							 AMERICA
NLS_CURRENCY							 $
NLS_ISO_CURRENCY						 AMERICA
NLS_NUMERIC_CHARACTERS						 .,
NLS_CALENDAR							 GREGORIAN
NLS_DATE_FORMAT 						 DD-MON-RR
NLS_DATE_LANGUAGE						 AMERICAN
NLS_CHARACTERSET						 AL32UTF8
NLS_SORT							 BINARY
NLS_TIME_FORMAT 						 HH.MI.SSXFF AM

PARAMETER							 VALUE
---------------------------------------------------------------- ----------------------------------------------------------------
NLS_TIMESTAMP_FORMAT						 DD-MON-RR HH.MI.SSXFF AM
NLS_TIME_TZ_FORMAT						 HH.MI.SSXFF AM TZR
NLS_TIMESTAMP_TZ_FORMAT 					 DD-MON-RR HH.MI.SSXFF AM TZR
NLS_DUAL_CURRENCY						 $
NLS_NCHAR_CHARACTERSET						 AL16UTF16
NLS_COMP							 BINARY
NLS_LENGTH_SEMANTICS						 BYTE
NLS_NCHAR_CONV_EXCP						 FALSE

```
Same code works with python 3.7.2 using the same environment variables and same database.

**Comment by anthony-tuininga** [comment]
I see the same behaviour. I'm not sure why yet, but I'll get back to you!

**Comment by anthony-tuininga** [comment]
Ok. I know why this is happening. Its historical behaviour which can't be changed at this late stage -- particularly since Python 2.7 only has about 9 months left to live. :-)

In Python 2.7, unicode data is transformed by cx_Oracle to NCHAR/NVARCHAR2 data in the database, but in Python 3, string data (which is the same as Unicode data in Python 2.7) is transformed to CHAR/VARCHAR2 data in the database. In retrospect that should never have happened -- but its too late to change now, unfortunately. In your coalesce statement, then, you are mixing CHAR and NCHAR data -- and that's not permissible. You can do one of the following two things:

1) pass a Python 2.7 string (drop the "u" prefix), which will then be transformed to CHAR/VARCHAR2
2) use cursor.setinputsizes(val=cx_Oracle.STRING) to tell cx_Oracle that you want to bind as CHAR/VARCHAR2

Both of these approaches should work in both Python 2 and 3.

**Comment by ancc** [comment]
Thanks! Option 2 works for me.

**Comment by anthony-tuininga** [comment]
Glad to hear it!

**Comment by helix84** [comment]
I ran into the same issue in a different context and your explanation helped me understand and resolve it. Posting it here in case someone else runs into it, too.

```
SELECT
 CASE source
    WHEN 'source1' THEN 'target1'
    WHEN 'source2' THEN 'target2'
    ELSE source                      -- cx_Oracle.DatabaseError: ORA-12704: character set mismatch
  END
FROM tab;
```

The problem was mixing NVARCHAR2 and VARCHAR2.

I changed it to this to make it work:
```
    ELSE CAST(source AS VARCHAR2(100))
```
