### ISSUE TITLE
Please make an rpm that's compatible with oracle-instantclient19.3

### ISSUE THREAD

**Issue by tyskjohan** [oracle/python-cx_Oracle#308]
Please make an rpm that's compatible with the 19c version of the Instant Client RPM's.

**Comment by anthony-tuininga** [comment]
A few notes regarding this:

1. Any cx_Oracle RPM that is built for cx_Oracle 6+ is automatically compatible with 19c versions of the instant client RPMs due to the fact that ODPI-C (on which cx_Oracle is based) dynamically loads that relevant client based on your configuration.
2. PyPI does not support storing RPMs. That is left up to the various vendors. Oracle Linux has RPMs available which you can find [here](http://yum.oracle.com/repo/OracleLinux/OL7/developer/x86_64/index.html). If you're looking for a different vendor you'll have to request it from them.
3. If you use a virtual environment (venv for Python 3 and virtualenv for Python 2) you can simply use ``python -m pip install cx_Oracle`` to install cx_Oracle.

**Comment by cjbj** [comment]
@anthony-tuininga the RPM dependency mechanism will pull in the IC the python RPM was built to depend on - which won't be 19c, since 19c RPMs are too new.

@tyskjohan At the next appropriate cx_Oracle release, the Linux team and ourselves will decide the IC dependency.  Since 19c connects to the same DBs as 12.2 & 18 clients, I don't see any problem.

I don't think the Linux team will rebuild current cx_Oracle RPMs with a new major IC release.
