### ISSUE TITLE
String comparison with fixed width character columns (CHAR/NCHAR)

### ISSUE THREAD

**Issue by agilevic** [oracle/python-cx_Oracle#365]
Since the beginning of (SQL) time the behavior for matching a string value to a fixed-width character column has been to ignore any padded spaces, a so called blank-padded semantics. For example:

```
CREATE TABLE T
(
    column1 NCHAR(4)
);

INSERT INTO T VALUES ('A');
```

In SQL*Plus the following statement returns one row as expected.

`SELECT * FROM T WHERE column1 = 'A'`

The same is true in Python DBAPI on cx_oracle:

`cur.execute("SELECT * FROM T WHERE column1 = 'A'")`

However, when using parameter binding, cx_oracle binds the string with with a cx_oracle.CHAR type, which according to your docs is Oracle's VARCHAR2 (confusing, but not the main point here). 

`cur.execute(""SELECT * FROM T WHERE column1 = :v", ['A'])`

That results in the non-padded comparison semantics and an empty result set. This is unexpected and a poor developer experience (DX). One way to avoid this is formally defining bound variable with cx_oracle.FIXED_CHAR, but In certain applications the column type may not be known at runtime. 

Is it possible to bind parameter with an "unspecified" type so as to achieve the same effect as sending the statement whole?

**Comment by anthony-tuininga** [comment]
> However, when using parameter binding, cx_oracle binds the string with with a cx_oracle.CHAR type, which according to your docs is Oracle's VARCHAR2 (confusing, but not the main point here).

By default, cx_Oracle binds strings as cx_Oracle.STRING (aka VARCHAR2) and you have to explicitly bind as cx_Oracle.FIXED_CHAR if you want fixed width character column support. Can you explain a bit more about cx_Oracle.CHAR (which doesn't exist!) and what part of the documentation you found confusing? Thanks!

> Is it possible to bind parameter with an "unspecified" type so as to achieve the same effect as sending the statement whole?

As far as I know there is no such concept, but perhaps @cjbj knows.

In general, you should use fixed width character columns only for fixed width data -- which wouldn't involve this difficulty. Of course if you're stuck with an existing database and have variable length data inside a fixed with character column then you will have to use cursor.setinputsizes() to tell cx_Oracle that you want to use fixed width semantics.

**Comment by agilevic** [comment]
@anthony-tuininga sorry, I was writing that from what I recalled without looking in the docs. You are right in that cx_Oracle.STRING is used by default. That's what I meant to say. 

The most confusing part is in cx_Oracle.NCHAR, which people can mistake for representing Oracle's NCHAR, whereas in fact it maps to NVARCHAR2. Makes it harder to use correctly and too easy to use incorrectly (DX again).

The question about achieving default behavior still stands and am sure a solution would be welcome by developer community. Ideally, when a type is not formally defined for a bound variable it should be up to the database server to resolve. That's what I imagine happens when query is sent without the use of parameters.

**Comment by anthony-tuininga** [comment]
Thanks for the clarification. Yes, the names of the various string types could be improved -- but since they've been this way for some time already, unfortunately we're stuck with them as they are, as changing them at this point would be even more confusing! One possibility, however, would be to create new constants -- DB_TYPE_VARCHAR, DB_TYPE_CHAR, DB_TYPE_NCHAR, DB_TYPE_NVARCHAR and so forth. The ones mandated by the DB-API would remain, of course and be effectively synonyms for the equivalent DB_TYPE_* constant. Will discuss with @cjbj and see if he thinks this would be worth the disruption.

**Comment by agilevic** [comment]
@anthony-tuininga thanks. Will you look into the other issue too?

**Comment by anthony-tuininga** [comment]
Yes, but I suspect that that issue isn't resolvable. I'd be happy to be proven wrong, though!

**Comment by anthony-tuininga** [comment]
I have pushed changes to master in [this commit](https://github.com/oracle/python-cx_Oracle/commit/f7b7785e82bb376ea04c104646d30dc1aa0ca06e) which create the new types and retain the old types as synonyms. Comments welcome! I believe this resolves this issue completely now.
