### ISSUE TITLE
SODA-equivalent of MongoDB's upsert would be very useful

### ISSUE THREAD

**Issue by jmcp** [oracle/python-cx_Oracle#382]
1. Review existing [enhancement requests](https://github.com/oracle/python-cx_Oracle/labels/enhancement)

Done. No existing enhancement requests match this.

2. Describe your new request in detail

When using MongoDB, you can use the `upsert` option to update a document *or* insert a new document if a document with the specified key does not already exist in the database. This would be very handy functionality to have with the SODA functionality of cx_Oracle.

https://api.mongodb.com/python/current/api/pymongo/collection.html?highlight=upsert

3. Give supporting information about tools and operating systems.  Give relevant product version numbers

I'm using OL7.7, cx_Oracle 7.3.0, DBEE 18.3.

**Comment by cjbj** [comment]
Tagging @morgiyan

**Comment by morgiyan** [comment]
@jmcp thanks for the request.

Could you describe your use-case a bit more... what's the exact "upsert" you're looking for? A filter driven one? For replaceOne, or update, or both?

We do have "save" methods in the pipeline. They are already available in SODA Java (see [saves](http://oracle.github.io/soda-for-java/oracle/soda/OracleCollection.html#saveAndGet-oracle.soda.OracleDocument-)) and SODA REST, but not yet available in cx_oracle. For a collection with client assigned keys, these methods do the following: if the document with the supplied key (i.e. document id) already exist in the collection, replace it with the input document. Otherwise, insert the input document. So these are key (i.e. id) driven upserts.

Would that meet your needs once it becomes available? Or are you looking specifically for a filter driven upsert as opposed to a key driven one ?

**Comment by jmcp** [comment]
@morgiyan Thankyou for the feedback. I'm looking for a key-driven method.

The particular use-case I've got where this would be useful involves keeping track of CVEs from NIST's National Vulnerability DB. The most up to date CVE reports do on occasion update CVEs that were previously reported, and I want to avoid (a) creating multiple documents with the same CVE id, and (b) avoid a lookup prior to insert.

What you mention re `saveAndGet()` will be fine for me when it's available in cx_Oracle. Thankyou

**Comment by morgiyan** [comment]
@jmcp, great, thank you. 

The only issue is that this requires underlying support for saveAndGet in OCI (Oracle Call Interface), which is the underlying C code cx_oracle is built on. This support has been added already, but the vehicle for its delivery is the next Oracle Database release (the instant client libraries that come with that). It's targeted for 2020 (unfortunately I am not allowed to give any exact dates).

To get it out sooner, we would have to look into backporting these to an earlier release, and I am not sure that will be allowed by the Oracle backporting process (since this is a new feature as opposed to a bug). If you really need it sooner, please let me know, and I can check whether backporting is at all doable in this case. Otherwise, you might need to work around it with a lookup for now (as you mentioned in (b)), until the next Oracle DB release (20c) libraries are out.

**Comment by cjbj** [comment]
The cx_Oracle code for this landed in the master branch in https://github.com/oracle/python-cx_Oracle/commit/44be2575345bb7129b80aecc5038b5e08a632d4a.  It needs Oracle Client 20c.

**Comment by anthony-tuininga** [comment]
cx_Oracle 8 was just released with these changes.
