### ISSUE TITLE
Consider providing standard python wheels instead of wininst executables

### ISSUE THREAD

**Issue by jobec** [oracle/python-cx_Oracle#39]
For windows installations there are now only `.exe` packages available in PyPi. Please consider providing standard `.whl` packages instead.

This allows to install cx_Oracle with standard `pip install` commands on windows, without the need to download them manually, convert them with `wheel convert path_to_package.exe` and then install it with `pip install`.

**Comment by cjbj** [comment]
There are .whl packages for cx_Oracle 6, which is currently Beta.  Try `python -m pip install cx_Oracle --pre`

**Comment by jobec** [comment]
Indeed, those are there for the Beta release. But I'm rather talking about the current stable version.

**Comment by cjbj** [comment]
There are no plans to provide them for cx_Oracle 5.  The runtime dynamic linking of the ODPI-C layer used by cx_Oracle 6 is what makes wheels possible.

**Comment by jobec** [comment]
It's actually simple to provide them. Just run the command `wheel convert path/to/exe.exe` and it outputs a wheel.

**Comment by anthony-tuininga** [comment]
The problem is that wheels don't support multiple versions for the same platform, Python version and bits (32-bit/64-bit). Since cx_Oracle 5 and earlier have Oracle version to contend with as well, providing a wheel would limit support to one Oracle version, which I don't want to do! I discussed this with the wheel format maintainers and there are no plans to change this. With cx_Oracle 6, Oracle version is no longer an issue so wheels are now produced.
