### ISSUE TITLE
Cannot insert with bind variables of hetergeneous types

### ISSUE THREAD

**Issue by iinuwa** [oracle/python-cx_Oracle#429]
I am using cx_Oracle version 7.3.0

I am having an issue inserting with a list bind variables containing heterogeneous types.

```python
cursor.execute('create table test (col1 varchar(100), col2 int)')
cursor.execute('insert into test VALUES (:1, :2)', parameters=["a", 2])
```
returns
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cx_Oracle.NotSupportedError: element 1 value is not the same type as previous elements
```

If I do this in SQL Developer and fill in the values, the row is inserted just fine.

**Comment by anthony-tuininga** [comment]
The problem is that you are passing a *keyword* parameter called `parameters` and cx_Oracle assumes that any keyword parameters are meant to indicate that you want to bind by name! Since the value passed is a list, it is assumed that this means a PL/SQL array and those must have the same type in each element of the array. Since you are using the bind variables :1 and :2 you should do this instead:

```
cursor.execute('insert into test VALUES (:1, :2)', ["a", 2])
```

If you did want to use bind by name you could do this instead:

```
cursor.execute('insert into test VALUES (:a, :b)', a="a", b=2)
```

**Comment by iinuwa** [comment]
D'oh! Sorry, that was me mixing up cx_Oracle and Airflow's abstraction over the cursor. Thanks for the help.
