### ISSUE TITLE
 DPI-1050: Oracle Client library is at version 10.2 but version 11.2 or higher is needed i wouldent under stand this err can aynone explain why like this error i will getting 

### ISSUE THREAD

**Issue by revanasidd** [oracle/python-cx_Oracle#442]
**See https://www.oracle.com/corporate/security-practices/assurance/vulnerability/reporting.html for how to report security issues**.

For other issues:

1. Is it an error or a hang or a crash?

2. What error(s) you are seeing?
**Cut and paste text showing the command you ran.  No screenshots.  Use a gist for long screen output and logs: see https://gist.github.com/**.

3. Include a runnable Python script that shows the problem.
Include all SQL needed to create the database schema.

4. Show the output of:

```
import sys
import platform

print("platform.platform:", platform.platform())
print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
print("platform.python_version:", platform.python_version())
```

And:

```
import cx_Oracle
print("cx_Oracle.version:", cx_Oracle.version)
print("cx_Oracle.clientversion:", cx_Oracle.clientversion())
```

5. What is your Oracle Database version?

**Comment by cjbj** [comment]
The error is because your environment is set to use Oracle Client libraries from version 10.
The current versions of cx_Oracle needs Oracle Client libraries from version 11.2 (or a later version)

The database can be a different version to the client.  If your database is 11.2 or later, you can use the latest 19c client libraries.

Review https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html
and https://cx-oracle.readthedocs.io/en/latest/user_guide/introduction.html#architecture

**Comment by revanasidd** [comment]
Thanks
