### ISSUE TITLE
subprocess.call() returning only zero after run query through cx_Oracle

### ISSUE THREAD

**Issue by andersontrindade0975** [oracle/python-cx_Oracle#447]
**See https://www.oracle.com/corporate/security-practices/assurance/vulnerability/reporting.html for how to report security issues**.

For other issues:

1. Is it an error or a hang or a crash?
It's a crash

2. What error(s) you are seeing?
After run a simple SQL statement through cx_Oracle, calling subprocess.call() to run external shell scripts are always returning zero, even if shell script returns non zero. It seens that cx_Oracle is "breaking" subprocess in some way.

3. Include a runnable Python script that shows the problem.

```
file testenv.py:

from os import environ
import cx_Oracle
import subprocess

class TestClass(object):
    
    def __init__(self):
        pass
            
    def exec_shell(self):
        print 'TestClass::exec_shell()'
        rc = subprocess.call('/tmp/orcl-callback.sh')
        print 'TestClass::exec_shell() -> os.call returned code {} from shell'.format(rc)
    
    def exec_query(self):
            conn = None
            cur = None
            print 'TestClass::exec_query(). Running select hello from dual'
            try:
                conn = cx_Oracle.connect(mode=cx_Oracle.SYSDBA)
                cur = conn.cursor()
                cur.execute("select 'hello' from dual")
                for v in cur:
                    print v
            except cx_Oracle.Error as e1:
                raise e1
            finally:
                if cur:
                    cur.close()
                if conn:
                    conn.close()        

def entrypoint():
    
    environ['ORACLE_HOME'] = '/u01/app/oracle/product/11.2.0.4/dbhome_ee'
    environ['ORACLE_SID'] = 'orcl'
    x = TestClass()
    x.exec_shell()
    x.exec_query()
    x.exec_shell()
    
if __name__=='__main__':
    entrypoint()
```

Below is a simple shell script that I'm calling. It returns 125 to simulate a return code

```
script orcl-callback.sh:

#!/bin/bash

echo "   This is a echo from shell script"
echo "   The shell will simulate an error, returning non zero code"
sleep 2
exit 125
```

4. Show the output of:

```
import sys
import platform

print("platform.platform:", platform.platform())
print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
print("platform.python_version:", platform.python_version())

('platform.platform:', 'Linux-3.10.0-1062.el7.x86_64-x86_64-with-oracle-7.7')
('sys.maxsize > 2**32:', True)
('platform.python_version:', '2.7.5')

```

And:

```
import cx_Oracle
print("cx_Oracle.version:", cx_Oracle.version)
print("cx_Oracle.clientversion:", cx_Oracle.clientversion())

('cx_Oracle.version:', '7.3.0')
('cx_Oracle.clientversion:', (11, 2, 0, 4, 0))
```

5. What is your Oracle Database version?

11.2.0.4.0

**Comment by cjbj** [comment]
This is what I get with Python 3.8 using Instant Client 19c on Linux and the current cx_Oracle master branch.  One (other) difference to you is that I was connected over SQL*Net, not using the 'bequeath' connection - I don't have Python on my DB server.

```
cjones@localhost:~/python$ python issue447.py 
TestClass::exec_shell()
   This is a echo from shell script
   The shell will simulate an error, returning non zero code
TestClass::exec_shell() -> os.call returned code 125 from shell
TestClass::exec_query(). Running select hello from dual
('hello',)
TestClass::exec_shell()
   This is a echo from shell script
   The shell will simulate an error, returning non zero code
TestClass::exec_shell() -> os.call returned code 125 from shell
```

**Comment by andersontrindade0975** [comment]
Thanks Christopher,

It seems that issue is related to bequeath connection. This is what I got with different setup:

```
Python 2.7, client 11g, SQL*Net:

    TestClass::exec_shell()
    This is a echo from shell script
    The shell will simulate an error, returning non zero code
    TestClass::exec_shell() -> os.call returned code 125 from shell
    TestClass::exec_query(). Running seelect hello from dual
    ('hello',)
    TestClass::exec_shell()
    This is a echo from shell script
    The shell will simulate an error, returning non zero code
    TestClass::exec_shell() -> os.call returned code 125 from shell

Python 3.6, client 11g, bequeath:

    TestClass::exec_shell()
    This is a echo from shell script
    The shell will simulate an error, returning non zero code
    TestClass::exec_shell() -> os.call returned code 125 from shell
    TestClass::exec_query(). Running seelect hello from dual
    ('hello',)
    TestClass::exec_shell()
    This is a echo from shell script
    The shell will simulate an error, returning non zero code
    TestClass::exec_shell() -> os.call returned code 0 from shell

Python 3.6, client 11g, TNS SQL*Net:

    TestClass::exec_shell()
    This is a echo from shell script
    The shell will simulate an error, returning non zero code
    TestClass::exec_shell() -> os.call returned code 125 from shell
    TestClass::exec_query(). Running seelect hello from dual
    ('hello',)
    TestClass::exec_shell()
    This is a echo from shell script
    The shell will simulate an error, returning non zero code
    TestClass::exec_shell() -> os.call returned code 125 from shell
```

As this program would be used by DBAs a support tool (on RDBMS server), the asked me to use bequeath as the usually sets the environment variables before run their tasks.

But TNS connection would be a workaround

**Comment by anthony-tuininga** [comment]
This is a duplicate of #376. There is another solution which should work for you as well. Namely, adding `BEQUEATH_DETACH=yes` to your `sqlnet.ora` configuration file. See the referenced issue for more details!

**Comment by anthony-tuininga** [comment]
This is just the way the Oracle Client library works, so not a bug in cx_Oracle at all.

**Comment by DaleW42** [comment]
It's odd to conclude that a module that breaks standard Python functionality can be considered not a bug, but hey, I guess that's easier than fixing it. The workaround offered isn't great since it requires changing something that might be out of one's control. Imagine having your Python code going around changing sqlnet.ora for a bug/not-a-bug.

For anyone else finding this, I found a much better workaround. Just do this before using subprocess to execute a command:
```
import signal
...
signal.signal(signal.SIGCHLD, signal.getsignal(signal.SIGCHLD))
```
This resets the handling of SIGCHLD that the Oracle library breaks and that cx_Oracle refuses to deal with. It's unclear if this only needs to be done once or if the Oracle client libraries continue to hijack the SIGCHLD signal handler.

**Comment by cjbj** [comment]
We'll pass your comments onto the owners of the Oracle Client shared libraries.

I'm not so happy with some of your terminology but appreciate you taking the time to comment and share your findings.

**Comment by DaleW42** [comment]
I'm not known for my diplomacy. I don't find it acceptable to produce a Python module that breaks standard Python functionality. The fact that the functionality is broken by the Oracle client libraries is irrelevant. cx_Oracle breaks subprocess. That is not acceptable and who that offends is not my concern. It's a cx_Oracle bug. Accept it and deal with it, or stop writing modules for Python. If I where to use ctypes to access Oracle client libraries myself then that's a different matter. Importing a Python module must not break Python. If it does the module is at fault.

Either stop the library from doing stupid things (good luck getting Oracle to fix this) or put a workaround in the module. It would be trivial to fix this in cx_Oracle, but instead the developers of cx_Oracle have decided breaking subprocess is acceptable. It is not. A library that hijacks a signal handler is a stupid library. The bug is obviously with the Oracle client libraries, so ideally get that fixed. Just don't be silly by claiming this is "just the way the Oracle Client library works".
