### ISSUE TITLE
Error when parsing data from an Oracle database

### ISSUE THREAD

**Issue by daveisfera** [oracle/python-cx_Oracle#507]
1. What versions are you using?
8.1.0 for module
12.2.0.1.ru-2020-07.rur-2020-07.r1 for database (it's an RDS database in AWS)

2. Is it an error or a hang or a crash?
Error

3. What error(s) or behavior you are seeing?
Data doesn't parse and this is output (see https://github.com/sqlalchemy/sqlalchemy/issues/5673):
```
Traceback (most recent call last):
  File \"/usr/src/app/test.py\", line 149, in _ingest
    ingest(table_api, org=table['org'], ext=table['ext'],
  File \"/usr/src/app/test.py\", line 526, in ingest
    for row in self.process_query(conn, update_query, column, value, batch_size,
  File \"/usr/src/app/test.py\", line 601, in process_query
    for record in conn.execute(curr_query):
  File \"/usr/src/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py\", line 1010, in __iter__ 
    row = self.fetchone()
  File \"/usr/src/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py\", line 1343, in fetchone 
    self.connection._handle_dbapi_exception(
  File \"/usr/src/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1514, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File \"/usr/src/app/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py\", line 182, in raise_
    raise exception
  File \"/usr/src/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py\", line 1336, in fetchone 
    row = self._fetchone_impl()
  File \"/usr/src/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py\", line 1215, in _fetchone_impl
    return self.cursor.fetchone()
ValueError: day is out of range for month
```

4. Include a runnable Python script that shows the problem.
I can't reproduce this by creating data manually and when I pull the data using DataGrip/PyCharm it outputs `1899-12-31 00:00:00` for the problematic value, but when I create a date with that value, I can read it just fine, so any ideas on how to make a reproducer or get the "actual" value that's causing the problem, then that would be helpful.

**Comment by anthony-tuininga** [comment]
I remember that there was a way to enter dates into an Oracle database that were incorrect by bypassing the normal checks that are performed. If that's the case, fetching that data will result in an error like this one. My suggestion is to determine which row (or rows) is causing the problem. You can do that by performing the query in a known order and printing the keys as you go so that you can narrow down the source of the problem data. Once you discover the row causing the problem you can perform a "dump" on that particular date using `select dump(bad_date_column) from table where key = 'bad_key'`. If it is incorrect you can fix the data and carry on. :-)

**Comment by daveisfera** [comment]
This is the output from running `dump()` on the bad column: `Typ=12 Len=7: 119,100,1,0,1,1,1`

**Comment by anthony-tuininga** [comment]
And if you store the value `1899-12-31 00:00:00` in a date column in the database and run `dump()` on it you get this instead: `Typ=12 Len=7: 118,199,12,31,1,1,1`. Looks to me like corrupted data. So I would just update it and move on!

**Comment by daveisfera** [comment]
Unfortunately, this is happening in a database that I don't have control over, so it will be hard to get this fixed. Is it possible to add support for parsing this?

**Comment by anthony-tuininga** [comment]
Since it is invalid data, how would you propose parsing this? I would think that the owners of the database would like to see this data corrected, don't you? If you select it in SQL*Plus, what does it show there? If this is a consistent value and the value returned by SQL*Plus is consistent, you could add a `decode()` to your query. But I would really recommend getting the data corrected.

**Comment by daveisfera** [comment]
I would prefer that it be `NULL` and the output from the Oracle tool was `NULL` as well, so I'd propose that as the "official" solution

**Comment by anthony-tuininga** [comment]
That suggestion would be unwise, I think. You would no longer be able to differentiate between invalid data and a real NULL value! I'll see what @cjbj thinks, too. I'd very much recommend getting the data fixed instead.

**Comment by cjbj** [comment]
Fixing the data is going to be much less problematic.

**Comment by daveisfera** [comment]
I agree that that's the best solution, but that's not always possible (as unfortunately is the case here because we don't have control of the database). The standard Oracle tools can query this data, so it seems like a tool like `cx_Oracle` should be able to read it as well.

**Comment by daveisfera** [comment]
I believe that I misspoke before and the Oracle tools are outputting the value as `1899-12-31` and not `NULL` like I stated before. But either way, there should be a way to process this data rather than just error out, so is that possible?

**Comment by cjbj** [comment]
The problem is you don't seem to have data: you have corruption. Making cx_Oracle return "1899-12-31 00:00:00" or NULL could be seen as a step backwards in ensuring accuracy of results, and for ensuring programs behave predictably. And there is even a security aspect to rejecting an invalid byte stream.

As a plain statement of fact: since the cx_Oracle code is available, you can always modify it to suit any special needs.

**Comment by daveisfera** [comment]
I agree that fixing the data is the ideal solution, but that's not always possible.

And probably more importantly, with the official Oracle tools and with the Java module to access Oracle databases, the data can be queried. With Python using this module it can't. Basically, there's a difference in behavior here and it's one that prevents any use of the data, so alignment with the official tools and other third party libraries feels like what the goal should be.

Also, could you clarify what the "security aspect" to this is? I mean if there really is one, then shouldn't that be raised with Oracle and the Java module to get that fixed?

**Comment by cjbj** [comment]
I appreciate you are in a position you'd rather not be in.  And any of your report results from other tools are going to be wrong or totally wacko until you fix the data - which can't be nice.

The general direction has been to tighten up in this area and I don't see cx_Oracle going against this.

**Comment by zzzeek** [comment]
can they apply a simple outconverter function here so that they can rework the date parsing in the manner they wish?

**Comment by anthony-tuininga** [comment]
Ah! Good suggestion for a workaround. :-)

**Comment by daveisfera** [comment]
@cjbj Sounds like your mind is already made up on this, but I'd just put in one last plug to fix the behavior to be aligned with the official Oracle and Java tools instead of this module making a new paradigm and raising an error.

**Comment by cjbj** [comment]
@daveisfera Sorry for the delay in responding.  I did discuss this up the management chain at the end of last week.  The conclusion was effectively that invalid dates are invalid and a general rule couldn't be applied.
