### ISSUE TITLE
ORA-24373 : Not able to set linesize

### ISSUE THREAD

**Issue by nitishnambiar** [oracle/python-cx_Oracle#529]
Hi,

I am using cx_oracle in python script to run multiple sql files to fetch some ~100 records per sql.

I am able to fetch the records, but getting ORA-24373 error invalid length specified for statement. 

I used to update linesize using SET LINESIZE option with sqlplus. 

I am trying to figure out if we have such option with cx_Oracle to get rid of this exception.

cx_Oracle version : 8.1.0
Oracle client : Oracle-instantclient19.3-basic
OS : Linux

Thanks!

**Comment by anthony-tuininga** [comment]
How long is the statement? The SET LINESIZE option in SQL*Plus is only intended to specify how many characters appear on a single line of OUTPUT, not the length of the SQL statement you are executing! You do get that message if you try the following:

**Comment by cjbj** [comment]
In case it's not clear to other readers, cx_Oracle only executes a single statement at a time.  A python script needs to be used to parse .SQL files into individual statements.  This is easiest if the syntax of the script is restricted, e.g. slashes are used instead of semi-colons to terminate statements.  See https://github.com/oracle/python-cx_Oracle/blob/8.1/samples/sample_env.py#L118-L151 for an example

**Comment by nitishnambiar** [comment]
Hi @anthony-tuininga / @cjbj , thanks for the update. I am running a multiple sql files with single query in each of them which were having 6-10 joins and was a long query. I understood my mistake, .sql files were have a semi-colon at the end of the query. I removed them and now they are working fine. Once again thanks for the sample.
