### ISSUE TITLE
Load binary file (eg. PDF, word,...) into collection using SODA

### ISSUE THREAD

**Issue by pinonino** [oracle/python-cx_Oracle#542]
Hi all,
I want to kindly ask you if is possible to load binary file like PDF, doc, ...   into a collection using SODA features.
If yes, please, can you provide an example?In addtion, is it possible to execute textual search on these binary files using SEARCH INDEX?

Below you can find the versions I'm using.

Thanks in advance.

Regards.

```
>>> print("platform.platform:", platform.platform())
platform.platform: Windows-10-10.0.18362-SP0
>>> print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
sys.maxsize > 2**32: True
>>> print("platform.python_version:", platform.python_version())
platform.python_version: 3.7.4
>>>
>>>
>>>
>>>
>>> print("cx_Oracle.version:", cx_Oracle.version)
cx_Oracle.version: 7.2.1
>>> print("cx_Oracle.clientversion:", cx_Oracle.clientversion())
cx_Oracle.clientversion: (18, 5, 0, 0, 0)
>>> print (con.version)
18.12.0.0.0```

**Comment by cjbj** [comment]
Tagging @morgiyan

**Comment by morgiyan** [comment]
@pinonino yes, you can create a SODA collection that can store any non-JSONs. As far as doing text searches of these types of files, such as Word and PDF, let me check with the indexing team and get back to you shortly.

**Comment by morgiyan** [comment]
Info on how to create a collection that can store Word, PDF, etc is below. I'll get back to you on the feasibility of the searching part, after speaking with the indexing team. 

At the time of creating the collection, pass the following meatdaata to [createCollection ](https://cx-oracle.readthedocs.io/en/latest/api_manual/soda.html?highlight=soda#SodaDatabase.createCollection):

{ "keyColumn" : { "name":"ID" }, 
  "contentColumn" : { "name" : "JSON_DOCUMENT", "sqlType" : "BLOB" }, 
  "versionColumn" : { "name" : "VERSION", "method" : "UUID" }, 
  "lastModifiedColumn" : { "name" : "LAST_MODIFIED" },
  "creationTimeColumn" : { "name" : "CREATED_ON" },
  "mediaTypeColumn" : {"name" : "MEDIA"}}

That will create a collection with the default shape, and, in addition to that, the media type column. Such a collection can store non-JSONs. Then the media type (aka mime type, i.e. application/pdf for PDF or  application/msword for word) for each document can be set when the document is created, prior to its insertion, using the [createDocument](https://cx-oracle.readthedocs.io/en/latest/api_manual/soda.html?highlight=soda#SodaDatabase.createDocument) method. The media type is passed as the value of the mediaType parameter of createDocument. SODA doesn't do anything with these media types, they are just stored as tags in the media type column.

If code snippet is needed, please let me know.

**Comment by pinonino** [comment]
Hi @morgiyan.
Thanks for you support.
If you can provide an example about creating a collection with metadata needed and how to load a binary file into a collection, I will appreciate it.

Thanks in advance.

**Comment by morgiyan** [comment]
Here we go. I'll get back to you on the searching part this week.

```
import cx_Oracle
from pathlib import Path

#Adjust the connect string as appropriate for your DB instance
conn = cx_Oracle.connect("username/password@host:port/serviceName")
conn.autocommit = True
db = conn.getSodaDatabase()

# Create a collection with a media type column. Such a collection can store non-JSONs

METADATA = '{ "keyColumn" : { "name":"ID" }, "contentColumn" : { "name" : "JSON_DOCUMENT", "sqlType" : "BLOB" }, "versionColumn" : { "name" : "VERSION", "method" : "UUID" }, "lastModifiedColumn" : { "name" : "LAST_MODIFIED" }, "creationTimeColumn" : { "name" : "CREATED_ON" }, "mediaTypeColumn" : {"name" : "MEDIA"}}'

coll = db.createCollection('myColl', METADATA);

# Read a binary file (e.g. PDF) into a bytes object
data = Path('/path/to/file/here/my.pdf').read_bytes()

# Create a SODA document with the content as the bytes object we read, and an appropriate media type. 
# The supplied media type is typically a mime type of the document. SODA doesn't do anything with it though,
# or use it in any way (e.g. for validation of the contents). It's just stored as a tag in the media type column
doc = db.createDocument(data, mediaType="application/pdf")

# Insert this document, and retrieve a result document (the latter will contain auto-generated components, such
# as the unique document key (aka ID), version, created timestamp, etc).
insertedDoc = coll.insertOneAndGet(doc);

# Just for fun, round-trip the document back. So we read
# this document back from the collection, by its unique key (aka ID).
doc = coll.find().key(insertedDoc.key).getOne();

# Write the contents of the retrived document back to another file. After this write,
# the new file should contain the same bytes as the original file

Path('/scratch/morgiyan/out.jpg').write_bytes(doc.getContentAsBytes());

```

**Comment by pinonino** [comment]
Hi @morgiyan.
Thank you.

Regards

**Comment by cjbj** [comment]
@morgiyan thanks.  I'll add that to the manual.

**Comment by morgiyan** [comment]
@pinonino getting back to you on the search part...

You can declare a regular text index on a SODA collection storing these binary docs that are textual in nature (e.g. PDF, Word, etc). For example, given the collection "myColl" created in the code snippet above, you can create the index as follows:

create search index indexNameHere on "myColl" (JSON_DOCUMENT);

Now the capability to search such a collection of binary documents from a SODA QBE query is not there yet. We can add it for you, it's a small enhancement. What's your timeline for needing this change?

In the meantime, you can try it directly from SQL:

select id from "myCol" where contains(JSON_DOCUMENT, 'always forward') > 0

This will select the unique key (i.e. ID) of the binary document containing the phrase "always forward". Obviously you can return the document bytes as well, by returning the JSON_DOCUMENT column. 

In the cx_oracle driver you can run SQL side-by-side with SODA operations. 

But what would be nicer is for us to provide an enhancement to do this contains search from SODA queries by example (QBEs), e.g.:

col.find().filter({"$contains" : "always forward"}).getCursor();

This would return all documents in the collection that have the phrase "always forward". All the other SODA functionality would apply as usual, e.g. you can combine it with skip/limit for pagination:

col.find().filter({$contains" : "always forward"}}.skip(10).limit(10).getCursor();

Please let us know your timeline, i.e. when do you need this functionality.

Two other things to note:

**1.** The column storing data in SODA collections is named JSON_DOCUMENT by default (since most collections store JSONs). In this case though, we're storing non-JSONs, so you could change the column name in the metadata you supply to create collection (here I changed JSON_DOCUMENT to just DOCUMENT):

METADATA = '{ "keyColumn" : { "name":"ID" }, "contentColumn" : { "name" : "**DOCUMENT**", "sqlType" : "BLOB" }, "versionColumn" : { "name" : "VERSION", "method" : "UUID" }, "lastModifiedColumn" : { "name" : "LAST_MODIFIED" }, "creationTimeColumn" : { "name" : "CREATED_ON" }, "mediaTypeColumn" : {"name" : "MEDIA"}}'`
 
If you do that, then the above index create statement and the SQL select would change the JSON_DOCUMENT part to just DOCUMENT.

**2.**  contains(...) operator used in the SQL doesn't just take words or phrases in the string it accepts as input. The string could also contain various text search operators as well (e.g. [near ](https://docs.oracle.com/en/database/oracle/oracle-database/19/ccref/oracle-text-CONTAINS-query-operators.html#GUID-70B60F42-A268-4A35-9297-D7A351ABA47E) for word proximity search). See [here](https://docs.oracle.com/en/database/oracle/oracle-database/19/ccref/oracle-text-CONTAINS-query-operators.html#GUID-6410B783-FC9A-4C99-B3AF-9E0349AA43D1) for details.

**Comment by pinonino** [comment]
Hi @morgiyan.
Thank you so much for you support.
We are planning to begin our project in a month.

Thanks and Regards.

**Comment by morgiyan** [comment]
@pinonino OK, thanks. Let me check on what we can do, I'll get back to you shortly. The fix itself is on the small side, but we need to see when/how we'd be able to get it out to you. The fix would be in the instant client libraries that cx_oracle relies on (no need to update cx_oracle driver itself).

**Comment by morgiyan** [comment]
@pinonino could you please tell us which instant client version and database version you're planning on using for this project. Thanks.

**Comment by pinonino** [comment]
@morgiyan we are plannig to use 18c and 19c for both Database and instant client.

Thanks and regards.

**Comment by pinonino** [comment]
Hi @morgiyan.
Are there any news?

Thanks in advance.

Regards.

**Comment by morgiyan** [comment]
@pinonino we're actively working on a fix for this. Let me check on the status with the person working on it, and we'll get back to you shortly.

One question - once we have the fix ready, will you need backports to both 19.x and 18.x clients, or is 19.x sufficient? Backporting to 19.x only would make it much simpler for us. A 19.x client will of course work with an 18.x DB. Please let us know.

**Comment by morgiyan** [comment]
@pinonino fix is close to getting completed, we'll need to figure out how to deliver the patch to you (the patch will be in instant client libraries only, no changes to the cx_oracle driver needed). It would be easiest to discuss by email, if possible. We can discuss which exact platform you need the fixes from, DBRU vs one-off fix, etc. 

Would you be able to drop me an email at:

maxim dot orgiyan at oracle dot com 

Replace dot with . and at with @ and remove the spaces.

Thank you.
