### ISSUE TITLE
Connection Subclass can't/shouldn't return a value from __init__

### ISSUE THREAD

**Issue by ctilly** [oracle/python-cx_Oracle#545]
Connection Subclass can't/shouldn't return a value from __init__

Is there any other way?

**Comment by cjbj** [comment]
For the sake of completeness, please fill in the https://raw.githubusercontent.com/oracle/python-cx_Oracle/master/.github/ISSUE_TEMPLATE/general-questions-and-runtime-problems.md template and provide a little snippet of code showing your problem. This is always helpful, even if only to show new users what the problem is.

**Comment by cjbj** [comment]
@ctilly ping.
