### ISSUE TITLE
Pool problem DPI-1010

### ISSUE THREAD

**Issue by Exzentttt** [oracle/python-cx_Oracle#598]
1. What versions are you using?

python 3.7
cx_Oracle 8.3

2. Describe the problem

![image](https://user-images.githubusercontent.com/41418703/147272265-d13a8fd4-0fc6-4063-8397-7baf7837a4c1.png)

3. Include a runnable Python script that shows the problem.

![image](https://user-images.githubusercontent.com/41418703/147272576-8aaf193d-3336-48ef-836c-380541230b0b.png)
![image](https://user-images.githubusercontent.com/41418703/147272628-d90005b4-c10f-474e-83cd-05376ea025be.png)

Hi, we are using version cx_Oracle 8.3.0 + aiohttp and faced a similar problem, after about time, a DPI-1080 error appears: connection was closed by ORA-2396 on some connections. Previously, there were no problems for six months, they started two weeks ago and we decided to upgrade to version 8.3.0 and saw such errors in the logs....

It seems that there are broken connections, how can this be overcome?

`self.pool = cx_Oracle.SessionPool(min=10, max=10, increment=0, threaded=True)`

**Comment by cjbj** [comment]
ORA-2396 means that your DBA has decided to kill 'idle' connections.  This isn't great when apps use pools, because the point of a pool is to have readily available connections when the app needs them.  Start by asking the DBA to remove the profile limitation.  Perhaps you can help your DBA by tuning your pool parameters to reduce DB load?

Decreasing [ping_interval](https://cx-oracle.readthedocs.io/en/latest/api_manual/session_pool.html#SessionPool.ping_interval) may help avoid ORA-2396 in some cases.  But will add some extra round-trips i.e. an increase in time.  With this feature, before `acquire()` returns, the pool can ping the DB to check if there is an error.  It can then recreate the connection and return the new one in the `acquire()` call.  Because this is timed behavior, it won't catch all cases.  The default of ping interval of 60 seconds has worked well for most cases.  With this feature, although the app may not see the ORA error, the  connection still needs to be recreated which slows the app - it is better to fix the resource profile so it doesn't kill idle sessions.  I do **not** recommend setting `ping_interval` to 0.

Apps should always check for errors after `execute()` etc. and do appropriate recovery.   This could include dropping a connection, recreating it, and then continuing.  If a connection has an error, then just close only that one connection.  **Avoid closing the whole pool**.  Closing the whole pool will cause all usable connections to give errors.  You don't want to do that.

PS.  please don't use screenshots.  Not everyone can read them.  Also we can't cut & paste from them!

**Comment by Exzentttt** [comment]
Thanks a lot for the answer and hints!

**Comment by cjbj** [comment]
Let us know how you go.

**Comment by Exzentttt** [comment]
Everything has stabilized, but there are problems when several connections become erroneous, we do a check and try to run execute again. As I understand it, now in version 8.3.0, with such an error, the connection is closed automatically. Unfortunately, we cannot influence the administrators now and create a separate user in the database.

**Comment by cjbj** [comment]
Even with older cx_Oracle versions the connections would have been closed automatically, but there were some improvements in 8.3.

What are the problems you are still seeing?

**Comment by Exzentttt** [comment]
@cjbj No problem, u can close this issue, thanks
