### ISSUE TITLE
a few elementary questions (autocommit, conection.handle and ping etc)

### ISSUE THREAD

**Issue by az-z** [oracle/python-cx_Oracle#60]
python 3.4.6, cx_oracle 6 pre1

Hello,
 i just wonder what is the right way to check if i do have a connection established? 
Any examples with connection.ping, handle - where do i use those and how?
Where/how do set connection.autocommit and connection.clientinfo?

**Comment by cjbj** [comment]
This is all a "high-availability" trade-off.

IMHO the only real way to check if a connection is usable is to execute the application statement you want run (and I don't mean `SELECT 1 FROM DUAL`).  This is because something could fail between any other kind of check and the eventual application statement execution.  You have to have error handling on your statements anyway, so make use of it. This error handling can be used to determine what class of error occurred, and take appropriate action e.g. dropping a bad connection, getting a new one, and then re-executing your statement.

People like pinging because it gives a (false) sense of security that applications will run without error, and they can simplify the above error code on the assumption that connection failures will be reduced (thus forcing users to have to restart an operation if there was a failure)

For long running applications use a session pool and release connections back to the pool when not in use.  If you have Oracle 12.2 client libraries, they will do a lightweight connection validation & automatic re-establishment (if necessary) when you next get a connection back from the pool.  Or with older Oracle client libraries you may want to explicitly 'ping' when you get a connection from the pool.  However each ping will take time, so you may only want to do it if the pool is not active and hence not able to detect errors since no statements are executing.  If you look at the [PHP OCI8](http://php.net/manual/en/oci8.configuration.php#ini.oci8.ping-interval) and [Node.js node-oracledb](https://github.com/oracle/node-oracledb/blob/v1.13.1/doc/api.md#propdbpoolpinginterval) APIs, they have a time based approach to pinging.

If you're concerned about high availability, check out the Oracle Net settings for timeouts.  They are common across OCI-based code (like cx_Oracle and node-oracledb): check out my recent notes at https://stackoverflow.com/a/45449862/4799035

Most apps would never autocommit, since that destroys transactional consistency when multiple statements make up a single logical transaction.  Also overcommitting causes the DB to do unnecessary work, so it slows down the whole system.  However there is a place for autocommit since an explicit commit will require a 'round trip' to the DB whereas autocommit will 'piggyback' the commit message on each SQL statement execution.  To go to extremes, applications should autocommit only the last statement of a transaction.

Clientinfo and related 'application information' settings are useful so DBA's can relate performance etc to what the application is executing.

**Comment by az-z** [comment]
Christopher
This is a trove of useful information. Thank you!
But where do I see how to set auto commit etc?

**Comment by anthony-tuininga** [comment]
The [documentation](http://cx-oracle.readthedocs.io/en/latest/connection.html#Connection.autocommit) should help you out.
