### ISSUE TITLE
Using Oracle built in functions such as SYSDATE in cursor.executemany() 

### ISSUE THREAD

**Issue by arulvenkatesh** [oracle/python-cx_Oracle#602]
1. What versions are you using?
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

platform.platform: Windows-10-10.0.17763-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.6.2

cx_Oracle.version: 8.2.1
cx_Oracle.clientversion: (12, 2, 0, 1, 0)

2. Describe the problem
How to use Oracle built in functions with cx_Oracle.executemany using bind variables. 

Getting the below error when inserting Sysdate 

ORA-01858: a non-numeric character was found where a numeric was expected
ORA-01858: a non-numeric character was found where a numeric was expected

The temp table column datatype is DATE

3. Include a runnable Python script that shows the problem.

```
import cx_Oracle

test_data = [ ('SYSDATE'),('SYSDATE-30')]
sql = "Insert into Temp (SNAP_D) values (:1)"

with cx_Oracle.connect(login, password, tns, encoding="UTF-8") as con:
        with con.cursor() as cur:           
              cur.executemany(sql, test_data )       
        con.commit()
```

**Comment by anthony-tuininga** [comment]
This is not unexpected! The data you are inserting is a string. And the strings you are providing cannot be converted to dates. You can do the following:

```
test_data = [(datetime.datetime.now(),), (datetime.datetime.now() - datetime.timedelta(30),)]
```

Or, if you prefer to use the database version instead you would have to do this:

```
cur.execute("insert into Temp (SNAP_D) values (sysdate)")
cur.execute("insert into Temp (SNAP_D) values (sysdate - 30)")
```

**Comment by cjbj** [comment]
If you are inserting a bunch of rows and want them all to have the same dates, other options including doing an initial SELECT to get the dates into Python variables, and then binding those variables in the `executemany()` call.  Or you could use a trigger that default the date column when no value is set in the INSERT.

**Comment by anthony-tuininga** [comment]
One other possibility:

```
test_data = [(0,), (30,)]
sql = "insert into Temp (SNAP_D) values (sysdate - :1)"
cur.executemany(sql, test_data)
```

It all depends on what you are trying to accomplish and if all of the rows are going to be derived from sysdate in some fashion.

**Comment by cjbj** [comment]
@arulvenkatesh go back to whoever designed the process and explain how inefficient it is!   It's also likely to be error prone (with respect to timezones can daylight savings time etc).  I can also see how there might be SQL injection security issues depending on your final solutions.  Convince the architect to use APEX instead of spreadsheets.

Fundamentally bind values have to be actual data values, since they are not treated as part of the SQL statement.

You seem to have a viable solution.  There might be others that are hackier and involve post-processing in PL/SQL.  I'll close this now.
