### ISSUE TITLE
cx_Oracle installation on redhat 6.7

### ISSUE THREAD

**Issue by bhaba20** [oracle/python-cx_Oracle#635]
Hi team, I need support in order to install cx_oracle on redhat 6.7 
![cx_oracle_installation](https://user-images.githubusercontent.com/112481827/187422993-9bd96322-832f-40d8-80d1-65a8e6a1cb36.PNG)

**Comment by cjbj** [comment]
You will probably just find it easier to install using `pip` instead of trying to get an RPM package for such an old OS. See the manual.  However there may be various issues to overcome, such as finding a version of Python & matching cx_Oracle.

(PS. please don't paste screenshots: not everyone can read them; we can't text-search in them, or cut & paste for replies)

**Comment by bhaba20** [comment]
Hi sir noted,
I will perform and feedback.

Thanks
