### ISSUE TITLE
Build failure with error " error: command 'gcc' failed: No such file or directory"

### ISSUE THREAD

**Issue by Vishal2696** [oracle/python-cx_Oracle#654]
1. What versions are you using?
8.3.0

2. Describe the problem
From June 26, 2023 My python application build is failing when trying to build the wheel of `cx-oracle` package with the below error. 
```

  ╰─> [14 lines of output]
      <string>:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      /tmp/pip-build-env-tn2v0pl_/overlay/lib/python3.11/site-packages/setuptools/config/expand.py:132: SetuptoolsWarning: File '/tmp/pip-install-tsgejqlj/cx-oracle_a53d28ab668f48939e0b608593e04b93/README.md' cannot be found
        return '\n'.join(
      running bdist_wheel
      running build
      running build_ext
      building 'cx_Oracle' extension
      creating build
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/odpi
      creating build/temp.linux-x86_64-cpython-311/odpi/src
      creating build/temp.linux-x86_64-cpython-311/src
      gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DCXO_BUILD_VERSION=8.3.0 -Iodpi/include -Iodpi/src -I/__w/34/DEX-Airflow-DAGS/3env/include -I/usr/local/include/python3.11 -c odpi/src/dpiConn.c -o build/temp.linux-x86_64-cpython-311/odpi/src/dpiConn.o
      error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cx-oracle

```
The URL path of the package that was downloaded when the above error occurred was `/pypi/download/cx-oracle/8.3/cx_Oracle-8.3.0.tar.gz`. 

Now to I initiated the same build from a different repo (Codes are 95% identical) and the build was surprisingly successful. The only difference I could spot from the build logs was that the URL path of the package was different. It was `pypi/download/cx-oracle/8.3/cx_Oracle-8.3.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl`
Can anyone point me what mistake this might be and IF I need to make any changes to my `setup.py` file? but in both repos the `setup.py` files are exact same.

**Comment by cjbj** [comment]
The best way forward is to upgrade cx_Oracle.  The new name is python-oracledb, see the [release announcement](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a).  This has pre-built binaries for Python 3.11 so you won't need to compile it on most operating systems.

The whl file you mention was for Python 3.8.  It's clean install on your other machine may have been because that machine used Python 3.8 and the package had a pre-built cx_Oracle binary for Python 3.8

If you want to continue with cx_Oracle, then the error seems to be that you don't have the gcc compiler installed:
