### ISSUE TITLE
cx_Oracle.DatabaseError: ORA-24454: client host name is not set

### ISSUE THREAD

**Issue by datalee** [oracle/python-cx_Oracle#79]
#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
64-bit

2. What is your version of cx_Oracle?
cx_Oracle-6.0.2-cp27-cp27mu-manylinux1_x86_64

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
   instantclient-basic-linux.x64-12.2.0.1.0
   vis：https://oracle.github.io/odpi/doc/installation.html#linux
4. What is your version of the Oracle Database?

5. What is your OS and version?
Red Hat 4.4.7-1
6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.
  4.6.3

7. What environment variables did you set?  How *exactly* did you set them?
export LD_LIBRARY_PATH=/opt/oracle/instantclient_12_2:$LD_LIBRARY_PATH

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?

9. What error(s) you are seeing?
>>> conn = cx_Oracle.connect('xx/xx@xxx.xxx.xx.xx/xxx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cx_Oracle.DatabaseError: ORA-24454: client host name is not set

**Comment by cjbj** [comment]
Thanks for the detail. In brief:

- Google
- set a hostname, e.g. in /etc/hosts
- if you can't set a hostname, consider setting using HOSTALIAS, see https://stackoverflow.com/questions/39201869/aws-python-lambda-with-oracle-oid-generation-failed

**Comment by datalee** [comment]
@cjbj  thanks，it works.

**Comment by cjbj** [comment]
@datalee I heard a rumor that you may simply be able to set ORACLE_HOSTNAME.  I can't reproduce the problem, so I can't verify.  Can you undo your changes and try setting ORACLE_HOSTNAME?

**Comment by cjbj** [comment]
Cancel that; I found an OL6 system I could reproduce it on; and ORACLE_HOSTNAME didn't seem to have an effect.

**Comment by davidjb** [comment]
For anyone needing to solve the issue, the my problem was that that cx_Oracle couldn't resolve my computer's hostname into a network address, not that I didn't have or needed to set a hostname.   The [Oracle documentation](https://docs.oracle.com/en/database/oracle/oracle-database/18/errmg/ORA-24280.html#GUID-7B2814DB-F946-4EB1-80B5-219B256E90C0) isn't clear at all:

> ORA-24454: client host name is not set
> Cause: The network host name in files like /etc/hosts was not set.
> Action: Set the host name and try again.

For me, it was that the `/etc/hosts` file on my Mac didn't have an entry for `davidjb.local` which was my computer's host name.  For those that don't know your hostname, you can get it either from the `hostname` command or `python -c 'import socket; print(socket.gethostname());'` if you want to be 100% sure of what Python thinks your hostname is.  Then, I took that name and added a new entry into `/etc/hosts`:

```
127.0.0.1	davidjb.local
```

And thus the problem was solved.  I can actually use any random IP address I want here and it seems to all still work so why cx_Oracle needs this, I don't currently know.  My existing code was working fine a few months back and I haven't adjusted my hostname or `/etc/hosts` file that I'm aware of.

@cjbj Fwiw, setting the environment variable `ORACLE_HOSTNAME` had no effect for me either.

Anyway, issue sorted and this is here for future generations to discover.

**Comment by felipenoris** [comment]
Looks like this happens on OSX 10.10.5, but not on new macOS 10.14.2 .

**Comment by pschmidtke** [comment]
> For anyone needing to solve the issue, the my problem was that that cx_Oracle couldn't resolve my computer's hostname into a network address, not that I didn't have or needed to set a hostname. The [Oracle documentation](https://docs.oracle.com/en/database/oracle/oracle-database/18/errmg/ORA-24280.html#GUID-7B2814DB-F946-4EB1-80B5-219B256E90C0) isn't clear at all:
> 
> > ORA-24454: client host name is not set
> > Cause: The network host name in files like /etc/hosts was not set.
> > Action: Set the host name and try again.
> 
> For me, it was that the `/etc/hosts` file on my Mac didn't have an entry for `davidjb.local` which was my computer's host name. For those that don't know your hostname, you can get it either from the `hostname` command or `python -c 'import socket; print(socket.gethostname());'` if you want to be 100% sure of what Python thinks your hostname is. Then, I took that name and added a new entry into `/etc/hosts`:
> 
> ```
> 127.0.0.1	davidjb.local
> ```
> And thus the problem was solved. I can actually use any random IP address I want here and it seems to all still work so why cx_Oracle needs this, I don't currently know. My existing code was working fine a few months back and I haven't adjusted my hostname or `/etc/hosts` file that I'm aware of.
> 
> @cjbj Fwiw, setting the environment variable `ORACLE_HOSTNAME` had no effect for me either.
> 
> Anyway, issue sorted and this is here for future generations to discover.

This is the actual answer that worked for me, not all the others.

**Comment by jonassteinberg1** [comment]
@davidjb's answer worked for me.  positively insane issue.

**Comment by cjbj** [comment]
@jonassteinberg1 what Oracle Client version do you have?  What OS are you on?
