### ISSUE TITLE
DPI-1054 error is raised when cursor is not closed, why?

### ISSUE THREAD

**Issue by ancc** [oracle/python-cx_Oracle#88]
Is this intentional that cursor needs to be closed explicitly starting from version 6?

Example
```python
>>> import cx_Oracle
>>> cx_Oracle.version
'6.0.2'
>>> con = cx_Oracle.Connection('dev/dev@dev')
>>> cur = con.cursor()
>>> cur.execute('select 1 from dual')
<cx_Oracle.Cursor on <cx_Oracle.Connection to dev@dev>>
>>> cur.fetchone()
(1,)
>>> con.close()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cx_Oracle.DatabaseError: DPI-1054: connection cannot be closed when open statements or LOBs exist
>>> 
```

On version 5.3 it works
```
>>> import cx_Oracle
>>> cx_Oracle.version
'5.3'
>>> con=cx_Oracle.Connection('dev/dev@dev')
>>> cur=con.cursor()
>>> cur.execute('select 1 from dual')
<cx_Oracle.Cursor on <cx_Oracle.Connection to dev@dev>>
>>> cur.fetchone()
(1,)
>>> con.close()
>>> 
```

**Comment by anthony-tuininga** [comment]
This is due to the fact that if you use a session pool and you release the connection without closing the cursors or LOBs associated with that connection you will get a leak. It was decided to avoid that situation and thus the new error was created. Technically, a standalone connection as you have used above doesn't have that issue so the problem could be ignored in that case -- but it was decided to have the code consistent in this case, too. In your example there is no need to call con.close() and in fact in most cases it is not necessary to call it explicitly. If you don't make the call explicitly the closes happen in the right order automatically and you won't get the DPI-1054 error. Hope that all makes sense and answers your question!

**Comment by ancc** [comment]
clear. Thanks!
